#!/usr/bin/bash -xe

d:
  npm run dev

c:
  npx astro check

f:
  npx prettier --write .

s:
  npx astro sync

b:
  npx astro build

p:
  npx astro preview

# paraglide-compile
pc:
  npm run paraglide-compile