#!/usr/bin/env bash

d:
  pnpm run dev

c:
  pnpx astro check

f:
  pnpx prettier --write .

s:
  pnpx astro sync

b:
  pnpx astro build

p:
  pnpx astro preview

# paraglide-compile
pc:
  pnpm run paraglide-compile
