#!/usr/bin/env bash

d:
  pnpm run dev

c:
  pnpm astro check

f:
  pnpm prettier --write .

s:
  pnpm astro sync

b:
  pnpm astro build

p:
  pnpm astro preview

# paraglide-compile
pc:
  pnpm run paraglide-compile
